name: Publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - "tracelib-python"
  workflow_dispatch:

permissions:
  id-token: write  # Critical for trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracelib-python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
            version: "latest"
            pyproject-file: "backend/pyproject.toml"
            enable-cache: true
            ignore-nothing-to-cache: true
            python-version: 3.11

      - name: Build package
        run: uv build --out-dir /github/workflows/dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/